version: '3.1'
services:
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,DOCKER_HACK://kafka:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,DOCKER_HACK:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    command: ["sh", "-c", "/usr/bin/kafka-topics --create --bootstrap-server kafka:9092,kafka:19092 --replication-factor 1 --partitions 1 --topic my_topic || true && /etc/confluent/docker/run"]
    networks:
      - my_network
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - my_network
  scheduler:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - my_network
  webserver:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - my_network
  triggerer:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - my_network
  postgres:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge