# Required connection configs for Kafka producer, consumer, and admin
bootstrap.servers=pkc-56d1g.eastus.azure.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
sasl.username=VTQFKF6R7ZQZRZIA
sasl.password=XQbZ2HZiQ6KdM0PtzvT2pbHwsHMwiselo3JdiElnHq9ilLrhGNzUlvlnUTqB6g5m

# Best practice for higher availability in librdkafka clients prior to 1.7
session.timeout.ms=45000

client.id=ccloud-python-client-2cb9eeb9-725a-4fe1-8816-282491dda9e7
